# Generated by Django 5.2.5 on 2025-08-26 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SomeDifferentParentModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SomeParentModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                (
                    "some_parent_decimal",
                    models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
                ),
                ("some_parent_date", models.DateField(auto_now=True, null=True)),
                ("some_parent_datetime", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="SomeRelatedModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SomeModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("some_decimal", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("some_date", models.DateField(auto_now=True)),
                ("some_datetime", models.DateTimeField(auto_now=True)),
                (
                    "some_other_different_parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="test_app.somedifferentparentmodel",
                    ),
                ),
                (
                    "some_other_parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="some_other_models",
                        to="test_app.someparentmodel",
                    ),
                ),
                (
                    "some_parent_model",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="some_models",
                        to="test_app.someparentmodel",
                    ),
                ),
                (
                    "some_related_models",
                    models.ManyToManyField(related_name="related_models", to="test_app.somerelatedmodel"),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="SomeChildModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                (
                    "some_child_decimal",
                    models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
                ),
                ("some_child_date", models.DateField(auto_now=True, null=True)),
                ("some_child_datetime", models.DateTimeField(auto_now=True, null=True)),
                (
                    "some_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="some_child_models",
                        to="test_app.somemodel",
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
    ]
